import type { Adventure, AdventureId } from "./types";

export const adventures: Adventure[] = [
  { id: "tram", place: "TRAMVAY DURAĞI", title: "Biletim yok ama…", hook: "Karizmam geçerli.", story: "Fındık şehrin en ciddi yolcusu gibi hazırlandı. Cam kenarı görevi artık resmî bir mesele.", task: "Fındık için en iyi pencere koltuğunu seç.", choices: ["Güneş alan pencere", "Kapının yanı", "Sürücünün koltuğu"], correctChoice: 0, reward: { xp: 25, sticker: "Yoldayım!", stickerText: "Yoldayım!", memory: "İlk tramvay görevi başarıyla tamamlandı." }, tone: "tram" },
  { id: "bike", place: "BİSİKLET YOLU", title: "Rüzgâr görevi", hook: "Kulaklar hazır mı?", story: "Rota belirlendi. Rüzgâr, kulaklar ve önemli yapraklar denetim altında.", task: "Rüzgârın uçurduğu en parlak yaprağı seç.", choices: ["Sol yaprak", "Altın yaprak", "Minik dal"], correctChoice: 1, reward: { xp: 25, sticker: "Geliyorum!", stickerText: "Geliyorum!", memory: "Rüzgâra karşı minik ama ciddi bir bisiklet turu." }, tone: "bike" },
  { id: "cafe", place: "MAHALLE KAFESİ", title: "Kafe gizli görevi", hook: "Kahveyi koklamak serbest.", story: "Fındık yalnızca masaları ve olası kurabiye hareketlerini profesyonelce denetliyor.", task: "Kurabiye kokusunun geldiği masayı bul.", choices: ["Pencere masası", "Yuvarlak masa", "Kitap köşesi"], correctChoice: 1, reward: { xp: 25, sticker: "Mola verdim.", stickerText: "Mola verdim.", memory: "Kafe güvenliği Fındık tarafından onaylandı." }, tone: "cafe" },
  { id: "park", place: "YEŞİL PARK", title: "Park keşfi", hook: "Her çalı araştırılacak.", story: "Çimenler kontrol edildi. Şimdi sıra en gizli patika işaretinde.", task: "Fındık'ın bulduğu doğru patika işaretini seç.", choices: ["Yaprak izi", "Kırmızı balon", "Mavi yıldız"], correctChoice: 0, reward: { xp: 25, sticker: "Keşifteyim!", stickerText: "Keşifteyim!", memory: "Parkın bütün önemli köşeleri keşfedildi." }, tone: "park" },
  { id: "night", place: "GECE BAHÇESİ", title: "Yıldız nöbeti", hook: "Uyumadan önce son görev.", story: "Gökyüzü sessiz. Fındık battaniyesini aldı; yıldızlar ise pek düzenli değil.", task: "Fındık'ın baktığı parlak yıldızı seç.", choices: ["Küçük yıldız", "Parlak yıldız", "Bulut"], correctChoice: 1, reward: { xp: 25, sticker: "İyi geceler.", stickerText: "İyi geceler.", memory: "Fındık ile ilk yıldız nöbeti." }, tone: "night" },
];

export const getAdventure = (id: AdventureId) => adventures.find((adventure) => adventure.id === id)!;
