const adventures=[
{id:'tram',place:'TRAMVAY DURAĞI',icon:'🚋',title:'Biletim yok ama…',hook:'Karizmam geçerli.',story:'Fındık şehrin en ciddi yolcusu gibi tramvaya bindi. Üç durak sonra bütün vagonun dikkatini dağıtmayı başardı. Görev: cam kenarını kap ve şehri profesyonelce izle.',xp:25,sticker:'🚋🐶',stickerText:'Yoldayım!',memory:'İlk tramvay görevi başarıyla tamamlandı.',theme:'#d8e8ee'},
{id:'bike',place:'BİSİKLET YOLU',icon:'🚲',title:'Rüzgâr görevi',hook:'Kulaklar hazır mı?',story:'Sepet kontrol edildi, rota belirlendi. Fındık bugün rüzgârı kulaklarında hissedecek. Atıştırmalık yok ama manzara puanı şimdiden 10/10.',xp:25,sticker:'🚲🐶',stickerText:'Geliyorum!',memory:'Rüzgâra karşı minik ama ciddi bir bisiklet turu.',theme:'#f0d8c6'},
{id:'cafe',place:'MAHALLE KAFESİ',icon:'☕',title:'Kafe gizli görevi',hook:'Kahveyi koklamak serbest.',story:'Fındık kahve içmiyor. Sadece masaları, kokuları ve olası kurabiye hareketlerini profesyonelce denetliyor. Fazlasıyla önemli bir görev.',xp:25,sticker:'☕🐶',stickerText:'Mola verdim.',memory:'Kafe güvenliği Fındık tarafından onaylandı.',theme:'#ead9c7'},
{id:'park',place:'YEŞİL PARK',icon:'🌳',title:'Park keşfi',hook:'Her çalı araştırılacak.',story:'Çimenler kontrol edilecek, çiçekler koklanacak ve şüpheli yapraklar incelenecek. Fındık bu görevi kişisel olarak çok ciddiye alıyor.',xp:25,sticker:'🌿🐶',stickerText:'Keşifteyim!',memory:'Parkın bütün önemli köşeleri keşfedildi.',theme:'#dce8cb'},
{id:'night',place:'GECE BAHÇESİ',icon:'🌙',title:'Yıldız nöbeti',hook:'Uyumadan önce son görev.',story:'Şehir sessizleşti. Fındık battaniyesini aldı ve gökyüzündeki yıldızları saymaya çıktı. Sayı biraz karıştı ama görev yine de başarılı.',xp:25,sticker:'🌙🐶',stickerText:'İyi geceler.',memory:'Fındık ile ilk yıldız nöbeti.',theme:'#d9d9ea'}];
const achievements=[{id:'first',icon:'🐾',name:'İlk Patika',test:s=>s.completed.length>=1},{id:'three',icon:'🗺️',name:'Gezgin',test:s=>s.completed.length>=3},{id:'all',icon:'🏆',name:'Minik Kaşif',test:s=>s.completed.length===5},{id:'boop',icon:'💚',name:'Burun Boop!',test:s=>s.boops>=5}];
const initial={xp:0,completed:[],boops:0,memories:[]};let state=load();let active=null;
function load(){try{return {...initial,...JSON.parse(localStorage.getItem('findik-universe-v1')||'{}')}}catch{return {...initial}}}function save(){localStorage.setItem('findik-universe-v1',JSON.stringify(state))}
function level(){return Math.floor(state.xp/100)+1}function greeting(){const h=new Date().getHours();if(h<6)return['Gece gezgini!','Fındık biraz uykulu ama seni gördü. 🌙'];if(h<12)return['Günaydın!','Fındık seni bekliyordu. ☀️'];if(h<18)return['Macera vakti!','Bugün dünya biraz daha büyük görünüyor.'];return['İyi akşamlar!','Fındık günün son macerasına hazır. ✨']}
function render(){const g=greeting();greetingEl.textContent=g[0];subGreeting.textContent=g[1];levelEl.textContent=level();const within=state.xp%100;xpText.textContent=`${within} / 100 XP`;xpBar.style.width=`${within}%`;completedCount.textContent=`${state.completed.length}/5 tamamlandı`;stickerCount.textContent=`${state.completed.length}/5 açık`;
adventureRail.innerHTML=adventures.map(a=>`<button class="adv ${state.completed.includes(a.id)?'done':''}" data-id="${a.id}" style="background:${a.theme}"><span class="kicker">${a.place}</span><span class="icon">${a.icon}</span><h3>${a.title}</h3><p>${a.hook}</p></button>`).join('');
document.querySelectorAll('.adv').forEach(b=>b.onclick=()=>openAdventure(b.dataset.id));
albumGrid.innerHTML=state.memories.length?state.memories.map(m=>{const a=adventures.find(x=>x.id===m.id);return `<article class="memory"><div class="photo" style="background:${a.theme}">${a.icon}🐶</div><b>${a.title}</b><small>${m.date} · ${a.memory}</small></article>`}).join(''):'<div class="empty">İlk maceranı tamamladığında hatıran burada yaşayacak. 📸</div>';
stickerGrid.innerHTML=adventures.map(a=>`<div class="sticker ${state.completed.includes(a.id)?'':'locked'}"><span>${state.completed.includes(a.id)?a.sticker:'🔒'}</span>${state.completed.includes(a.id)?a.stickerText:'Kilitli'}</div>`).join('');
achievementGrid.innerHTML=achievements.map(a=>{const ok=a.test(state);return `<div class="achievement ${ok?'':'locked'}"><span>${ok?a.icon:'🔒'}</span>${a.name}</div>`}).join('')}
function openAdventure(id){active=adventures.find(a=>a.id===id);modalIcon.textContent=active.icon;modalPlace.textContent=active.place;modalTitle.textContent=active.title;modalStory.textContent=active.story;modalReward.textContent=state.completed.includes(id)?'Bu macerayı daha önce tamamladın. Tekrar gezebilirsin. 💚':`Ödül: +${active.xp} XP · “${active.stickerText}” stickerı`;completeAdventure.textContent=state.completed.includes(id)?'Tekrar gezdim 🐾':'Macera tamamlandı ✨';adventureModal.showModal()}
function finish(){if(!active)return;if(!state.completed.includes(active.id)){state.completed.push(active.id);state.xp+=active.xp;state.memories.unshift({id:active.id,date:new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'short',year:'numeric'}).format(new Date())});save();navigator.vibrate?.([35,35,55])}adventureModal.close();speech.textContent=`${active.icon} ${active.memory}`;render()}
const reactions=['Burnuma mı dokundun? 😌','Bugün tramvaya mı binsek? 🚋','Atıştırmalık kontrolü yapıyorum.','Küçük patiler. Büyük planlar.','Tamam, hazırım! Nereye gidiyoruz?'];findik.onclick=()=>{state.boops++;save();speech.textContent=reactions[Math.floor(Math.random()*reactions.length)];findik.animate([{transform:'translateX(-50%) rotate(0)'},{transform:'translateX(-50%) rotate(-5deg) scale(1.05)'},{transform:'translateX(-50%) rotate(4deg)'},{transform:'translateX(-50%) rotate(0)'}],{duration:480});navigator.vibrate?.(30);render()};closeModal.onclick=()=>adventureModal.close();completeAdventure.onclick=finish;levelButton.onclick=()=>{levelTitle.textContent=`Seviye ${level()}`;levelCopy.textContent=`Birlikte ${state.completed.length} macera tamamladınız ve ${state.xp} XP topladınız. Fındık'ın dünyası keşfettikçe büyüyecek.`;levelModal.showModal()};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js'));const greetingEl=document.getElementById('greeting'),levelEl=document.getElementById('level');render();
